version: '3.1'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      SA_PASSWORD: a
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ../mssqldata:/var/opt/mssql
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
